### PR TITLE
[RFC] logging to file

### PR DESCRIPTION
**Pull request by geier**
I'm looking for some general feedback on this before I add docstrings and documentation. I'm also unsure about `logger.handlers = [_default_handler] ` (why are you using this and not `addHandler()`?) and removing all handlers and setting the filehandler if logger is already set (when would that be the case)?

### CODE REVIEW

**Comment by untitaker** [comment]
> I'm also unsure about logger.handlers = [_default_handler] (why are you using this and not addHandler()?) 

To remove other handlers that may have been inherited from root or elsewhere. I don't want to deal with bugreports a la "doubled output" because somebody registered their own stdout handler in addition.

Regarding your PR, the `basic_config` function allows you to pass your own logger which can be configured as you like. Isn't that sufficient?

**Comment by geier** [comment]
Using `basic_config` would work for me, if not for the `logger.handlers = [_default_handler]` line, which removes my handler.

But this could all be a problem of two modules meeting here which I haven't look into that much (click and logging).

You can see my try at pimutils/khal#676.

**Comment by untitaker** [comment]
Ah yes of course. In that case I would prefer a parameter to specify the
handlers to set.

**Comment by geier** [comment]
Chose other approach in khal, thanks for your help.

**Pull request closed without merging**
