### PR TITLE
Fix parsing of unicode logs.

### PR DESCRIPTION
**Pull request by kdeldycke**
Also tests funky multilines rendering with excessive spaces.

### CODE REVIEW

**Comment by untitaker** [comment]
Hey thanks for the fix, however I'd prefer if you made a separate testcase for unicode.

**Comment by kdeldycke** [comment]
Thanks @untitaker for the feedback. Just comited the change in c8c2fecdb0dca5602583c0f9eab55ebb1160e7d3.

**Comment by kdeldycke** [comment]
This PR is ready to be merged.

**Comment by untitaker** [comment]
Released 0.1.5.

**Comment by kdeldycke** [comment]
Thanks @untitaker for the release! :)

**Comment by untitaker** [comment]
I reverted this commit in master because this fix breaks Python 3 and released an alternative fix in 0.1.7.

**Comment by kdeldycke** [comment]
Thanks @untitaker for the follow-up. And sorry for the mess... :disappointed_relieved:

Thinking of that, maybe we should replace the whole string handling munbo-jumbo by a simple call to [`click.echo()`](http://click.pocoo.org/6/utils/#printing-to-stdout), since the later was designed to digest all string-related idiosyncrasies in Python.

**Comment by untitaker** [comment]
Unfortunately we're only in a formatter and don't directly output to console. This error is happening at a different level. I think I fixed everything in master though.

**Comment by kdeldycke** [comment]
Ah yes, you're right. I forgot about all these wrapping layers! :innocent:

**Pull request merged**
