### PR TITLE
switch from Travis to GitHub actions

### PR DESCRIPTION
**Pull request by nedbat**
I kept all the old Python versions, but added new ones up to 3.10.  You can decide to drop old versions or not.

(It doesn't work yet!)

### CODE REVIEW

**Comment by nedbat** [comment]
The tests run: https://github.com/nedbat/click-log/actions/runs/1973592918

But you need to decide what to do about old Python versions.  click now requires >=3.7.

**Review by untitaker — COMMENTED** [review]
i'm fine with droppign everything below 3.7 and use the same package metadata as click regarding that. thanks for your work!

**Comment by nedbat** [comment]
OK, I also dropped Pythons <3.7.  This is ready.

**Comment by untitaker** [comment]
thank you!

**Pull request merged**
